/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Dimension;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Dave van Rijn, IS-103, Studentnummer 500714558
 */
public class Chart extends javax.swing.JPanel {

    private final DecimalFormat deciForm = new DecimalFormat("0.00");
    /**
     * Creates new form Chart
     */
    public Chart() {
        initComponents();
    }

    public Chart(JPanel chartPanel, ArrayList<String> categorien, ArrayList<Double> bedragen) {
        this();
        chartPanel.setPreferredSize(new Dimension(550, 500));
        pnlChart.getViewport().removeAll();
        pnlChart.getViewport().add(chartPanel);
        StringBuilder builder = new StringBuilder();
        for (int i = 0; i < categorien.size(); i++) {
            builder.append(categorien.get(i));
            builder.append(" - ");
            builder.append("\u20ac");
            builder.append(deciForm.format(bedragen.get(i)));
            builder.append("\n\n");
        }
        txtChart.setText(builder.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlChart = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtChart = new javax.swing.JTextArea();
        lblCategorien = new javax.swing.JLabel();
        lblDisclaim = new javax.swing.JLabel();

        pnlChart.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        pnlChart.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtChart.setEditable(false);
        txtChart.setColumns(20);
        txtChart.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtChart.setLineWrap(true);
        txtChart.setRows(5);
        txtChart.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtChart);

        lblCategorien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCategorien.setText("Categorieën");

        lblDisclaim.setText("<html>Deze grafiek is gebaseerd op de toegepaste<br>filters van het overzicht.</html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategorien)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDisclaim)))
                .addComponent(pnlChart, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChart)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCategorien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDisclaim)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCategorien;
    private javax.swing.JLabel lblDisclaim;
    private javax.swing.JScrollPane pnlChart;
    private javax.swing.JTextArea txtChart;
    // End of variables declaration//GEN-END:variables
}
