/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import enums.Gebruiker;
import java.awt.Color;
import java.awt.Font;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import system.Database;
import system.Main;

/**
 *
 * @author Dave van Rijn, Klas IS-103, Studentnummer 500714558
 */
public class Gegevens extends javax.swing.JPanel {

    double saldo;
    int rekeningnummer;
    String voorletters, achternaam, tussenvoegsel, saldoString, rekeningnummerString;
    DecimalFormat form = new DecimalFormat("0.00");

    /**
     * Creates new form Gegevens
     */
    public Gegevens() {
        initComponents();
        setLetterGrootte(Main.getLetterGrootte());
        txtVoorletters.setText(Gebruiker.getVoorletters());
        txtTussenvoegsel.setText(Gebruiker.getTussenvoegsel());
        txtAchternaam.setText(Gebruiker.getAchternaam());
        txtRekeningnummer.setText(Integer.toString(Gebruiker.getRekeningnummer()));
        txtHuidigSaldo.setText(form.format(Gebruiker.getBudget()));
        checkRoodSaldo();
    }
    
    private void setLetterGrootte(int grootte){
        Font font = new Font("Tahoma", 0, grootte);
        lblAchternaam.setFont(font);
        lblVoorletters.setFont(font);
        lblTussenvoegsel.setFont(font);
        lblRekeningnummer.setFont(font);
        lblHuidigSaldo.setFont(font);
        txtAchternaam.setFont(font);
        txtVoorletters.setFont(font);
        txtTussenvoegsel.setFont(font);
        txtRekeningnummer.setFont(font);
        txtHuidigSaldo.setFont(font);
        btnOpslaan.setFont(font);
    }

    private void checkRoodSaldo() {
        if (!txtHuidigSaldo.getText().equals("0.00") && !txtHuidigSaldo.getText().equals("0,00")) {
            if (Gebruiker.getBudget() < 0) {
                txtHuidigSaldo.setForeground(Color.RED);
            } else {
                txtHuidigSaldo.setForeground(Color.BLACK);
            }
        } else {
            txtHuidigSaldo.setForeground(Color.BLACK);
        }
    }

    private void opslaan() {
        Database db = new Database();
        boolean correctIngevuld;
        voorletters = txtVoorletters.getText();
        tussenvoegsel = txtTussenvoegsel.getText();
        achternaam = txtAchternaam.getText();
        saldoString = txtHuidigSaldo.getText();
        rekeningnummerString = txtRekeningnummer.getText();

        if (saldoString.contains(",")) {
            saldoString = saldoString.replace(",", ".");
        }

        try {
            saldo = Double.parseDouble(saldoString);
            correctIngevuld = true;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Het huidige saldo bestaat alleen "
                    + "uit (decimale) getallen!", "Fout", JOptionPane.ERROR_MESSAGE);
            correctIngevuld = false;
        }

        if (correctIngevuld) {
            try {
                rekeningnummer = Integer.parseInt(rekeningnummerString);
                correctIngevuld = true;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Het rekeningnummer bestaat alleen "
                        + "uit getallen!", "Fout", JOptionPane.ERROR_MESSAGE);;
                correctIngevuld = false;
            }
        }

        if (correctIngevuld) {
            db.wijzigGebruiker(voorletters, tussenvoegsel, achternaam, rekeningnummer, saldo);
            Gebruiker.setGebruiker(voorletters, tussenvoegsel, achternaam, rekeningnummer, saldo);
            JOptionPane.showMessageDialog(null, "De gegevens zijn gewijzigd",
                    "Succes", JOptionPane.INFORMATION_MESSAGE);
            Main.setLabels();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAchternaam = new javax.swing.JLabel();
        lblVoorletters = new javax.swing.JLabel();
        lblTussenvoegsel = new javax.swing.JLabel();
        lblRekeningnummer = new javax.swing.JLabel();
        lblHuidigSaldo = new javax.swing.JLabel();
        txtVoorletters = new javax.swing.JTextField();
        txtAchternaam = new javax.swing.JTextField();
        txtTussenvoegsel = new javax.swing.JTextField();
        txtRekeningnummer = new javax.swing.JTextField();
        txtHuidigSaldo = new javax.swing.JTextField();
        btnOpslaan = new javax.swing.JButton();

        lblAchternaam.setText("Achternaam");

        lblVoorletters.setText("Voorletters");

        lblTussenvoegsel.setText("Tussenvoegsel");

        lblRekeningnummer.setText("Rekeningnummer");

        lblHuidigSaldo.setText("Huidig saldo");

        txtVoorletters.setText("Voorletters");
        txtVoorletters.setNextFocusableComponent(txtTussenvoegsel);
        txtVoorletters.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVoorlettersFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVoorlettersFocusLost(evt);
            }
        });

        txtAchternaam.setText("Achternaam");
        txtAchternaam.setNextFocusableComponent(txtRekeningnummer);
        txtAchternaam.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAchternaamFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAchternaamFocusLost(evt);
            }
        });

        txtTussenvoegsel.setText("Tussenvoegsel");
        txtTussenvoegsel.setNextFocusableComponent(txtAchternaam);
        txtTussenvoegsel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTussenvoegselFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTussenvoegselFocusLost(evt);
            }
        });

        txtRekeningnummer.setText("Rekeningnummer");
        txtRekeningnummer.setNextFocusableComponent(txtHuidigSaldo);
        txtRekeningnummer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRekeningnummerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRekeningnummerFocusLost(evt);
            }
        });

        txtHuidigSaldo.setText("Huidig saldo");
        txtHuidigSaldo.setNextFocusableComponent(txtVoorletters);
        txtHuidigSaldo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHuidigSaldoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHuidigSaldoFocusLost(evt);
            }
        });

        btnOpslaan.setText("Opslaan");
        btnOpslaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpslaanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnOpslaan)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblHuidigSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(txtHuidigSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblRekeningnummer, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(txtRekeningnummer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblAchternaam, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(txtAchternaam, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTussenvoegsel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(txtTussenvoegsel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblVoorletters, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(txtVoorletters, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(301, 301, 301))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVoorletters, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVoorletters, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTussenvoegsel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTussenvoegsel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAchternaam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAchternaam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRekeningnummer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRekeningnummer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHuidigSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHuidigSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnOpslaan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtVoorlettersFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVoorlettersFocusGained
        if (txtVoorletters.getText().equals(Gebruiker.getVoorletters())) {
            txtVoorletters.setText("");
        }

    }//GEN-LAST:event_txtVoorlettersFocusGained

    private void txtVoorlettersFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVoorlettersFocusLost
        if (txtVoorletters.getText().isEmpty()) {
            txtVoorletters.setText(Gebruiker.getVoorletters());
        }
    }//GEN-LAST:event_txtVoorlettersFocusLost

    private void txtTussenvoegselFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTussenvoegselFocusGained
        if (txtTussenvoegsel.getText().equals(Gebruiker.getTussenvoegsel())) {
            txtTussenvoegsel.setText("");
        }
    }//GEN-LAST:event_txtTussenvoegselFocusGained

    private void txtTussenvoegselFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTussenvoegselFocusLost
        if (txtTussenvoegsel.getText().isEmpty()) {
            txtTussenvoegsel.setText(Gebruiker.getTussenvoegsel());
        }
    }//GEN-LAST:event_txtTussenvoegselFocusLost

    private void txtAchternaamFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAchternaamFocusGained
        if (txtAchternaam.getText().equals(Gebruiker.getAchternaam())) {
            txtAchternaam.setText("");
        }
    }//GEN-LAST:event_txtAchternaamFocusGained

    private void txtAchternaamFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAchternaamFocusLost
        if (txtAchternaam.getText().isEmpty()) {
            txtAchternaam.setText(Gebruiker.getAchternaam());
        }
    }//GEN-LAST:event_txtAchternaamFocusLost

    private void txtRekeningnummerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRekeningnummerFocusGained
        if (txtRekeningnummer.getText().equals(Integer.toString(Gebruiker.getRekeningnummer()))) {
            txtRekeningnummer.setText("");
        }
    }//GEN-LAST:event_txtRekeningnummerFocusGained

    private void txtRekeningnummerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRekeningnummerFocusLost
        if (txtRekeningnummer.getText().isEmpty()) {
            txtRekeningnummer.setText(Integer.toString(Gebruiker.getRekeningnummer()));
        }
    }//GEN-LAST:event_txtRekeningnummerFocusLost

    private void txtHuidigSaldoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHuidigSaldoFocusGained
        if (txtHuidigSaldo.getText().equals(form.format(Gebruiker.getBudget()))) {
            txtHuidigSaldo.setText("");
        }
    }//GEN-LAST:event_txtHuidigSaldoFocusGained

    private void txtHuidigSaldoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHuidigSaldoFocusLost
        if (txtHuidigSaldo.getText().isEmpty()) {
            txtHuidigSaldo.setText(form.format(Gebruiker.getBudget()));
        }
        checkRoodSaldo();
    }//GEN-LAST:event_txtHuidigSaldoFocusLost

    private void btnOpslaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpslaanActionPerformed
        opslaan();
    }//GEN-LAST:event_btnOpslaanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpslaan;
    private javax.swing.JLabel lblAchternaam;
    private javax.swing.JLabel lblHuidigSaldo;
    private javax.swing.JLabel lblRekeningnummer;
    private javax.swing.JLabel lblTussenvoegsel;
    private javax.swing.JLabel lblVoorletters;
    private javax.swing.JTextField txtAchternaam;
    private javax.swing.JTextField txtHuidigSaldo;
    private javax.swing.JTextField txtRekeningnummer;
    private javax.swing.JTextField txtTussenvoegsel;
    private javax.swing.JTextField txtVoorletters;
    // End of variables declaration//GEN-END:variables
}
