/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import system.Database;
import system.Main;

/**
 *
 * @author Dave van Rijn, IS-103, Studentnummer 500714558
 */
public class Hypotheken extends javax.swing.JPanel {

    DecimalFormat deciForm = new DecimalFormat("0.00");

    /**
     * Creates new form Hypotheken
     */
    public Hypotheken() {
        Database db = new Database();
        initComponents();
        setLetterGrootte(Main.getLetterGrootte());
        tblHypotheken.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    JTable target = (JTable) e.getSource();
                    int row = target.getSelectedRow();
                    int id = (int) target.getValueAt(row, 0);
                    String soort = (String) target.getValueAt(row, 1);
                    Main.setNewPanel(new Hypotheek_NewEdit(id, soort));
                }
            }
        });
        vulTabel(db.getHypotheekTabel());
    }

    private void setLetterGrootte(int grootte) {
        Font font = new Font("Tahoma", 0, grootte);
        btnToevoegen.setFont(font);
        jLabel1.setFont(font);
        lblAantal.setFont(font);
        if (grootte == 19) {
            tblHypotheken.setFont(new Font("Tahoma", 0, 24));
        } else {
            tblHypotheken.setFont(new Font("Tahoma", 0, 16));
        }
    }

    private void vulTabel(ResultSet rs) {
        try {
            while (tblHypotheken.getRowCount() > 0) {
                ((DefaultTableModel) tblHypotheken.getModel()).removeRow(0);
            }
            int columns = rs.getMetaData().getColumnCount();
            while (rs.next()) {
                Object[] row = new Object[columns];
                for (int i = 1; i <= columns; i++) {
                    if (i == 3) {
                        row[i - 1] = deciForm.format(rs.getObject(i));
                    } else {
                        row[i - 1] = rs.getObject(i);
                    }
                }
                ((DefaultTableModel) tblHypotheken.getModel()).insertRow(rs.getRow() - 1, row);
            }
            rs.close();
        } catch (SQLException e) {
            Main.showError("043", e);
        }

        lblAantal.setText("Aantal hypotheken: " + tblHypotheken.getRowCount());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHypotheken = new javax.swing.JTable();
        btnToevoegen = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblAantal = new javax.swing.JLabel();

        tblHypotheken.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblHypotheken.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Soort", "Restschuld"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHypotheken.setColumnSelectionAllowed(true);
        tblHypotheken.setRowHeight(30);
        tblHypotheken.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblHypotheken);
        tblHypotheken.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tblHypotheken.getColumnModel().getColumnCount() > 0) {
            tblHypotheken.getColumnModel().getColumn(0).setResizable(false);
            tblHypotheken.getColumnModel().getColumn(1).setResizable(false);
            tblHypotheken.getColumnModel().getColumn(2).setResizable(false);
        }

        btnToevoegen.setText("Hypotheek Toevoegen");
        btnToevoegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToevoegenActionPerformed(evt);
            }
        });

        jLabel1.setText("Dubbelklik op een hypotheek om de details te weergeven.");

        lblAantal.setText("Aantal Hypotheken:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblAantal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 362, Short.MAX_VALUE)
                        .addComponent(btnToevoegen)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnToevoegen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAantal)
                .addGap(5, 5, 5))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnToevoegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToevoegenActionPerformed
        Main.setNewPanel(new Hypotheek_NewEdit());
    }//GEN-LAST:event_btnToevoegenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnToevoegen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAantal;
    private javax.swing.JTable tblHypotheken;
    // End of variables declaration//GEN-END:variables
}
