/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Font;
import system.Main;

/**
 *
 * @author Dave van Rijn, IS-103, Studentnummer 500714558
 */
public class Instellingen extends javax.swing.JPanel {

    private static int letterGrootte = Main.getLetterGrootte();

    /**
     * Creates new form Instellingen
     */
    public Instellingen() {
        initComponents();
        setLetterGrootte(letterGrootte);
    }

    private void setLetterGrootte(int letterGrootte) {
        Font font = new Font("Tahoma", 0, letterGrootte);
        btnGroter.setFont(font);
        btnKleiner.setFont(font);
        txtTest.setFont(font);
        btnOpslaan.setFont(font);
        lblFormaat.setFont(font);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroter = new javax.swing.JButton();
        btnKleiner = new javax.swing.JButton();
        btnOpslaan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTest = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        lblFormaat = new javax.swing.JLabel();

        btnGroter.setText("Grote tekst");
        btnGroter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroterActionPerformed(evt);
            }
        });

        btnKleiner.setText("Normale tekst");
        btnKleiner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKleinerActionPerformed(evt);
            }
        });

        btnOpslaan.setText("Opslaan");
        btnOpslaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpslaanActionPerformed(evt);
            }
        });

        txtTest.setEditable(false);
        txtTest.setColumns(20);
        txtTest.setLineWrap(true);
        txtTest.setRows(5);
        txtTest.setText("Dit is een voorbeeld");
        txtTest.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtTest);

        lblFormaat.setText("Tekstformaat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnKleiner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGroter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnOpslaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(94, 94, 94)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(342, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFormaat)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblFormaat)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGroter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnKleiner, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOpslaan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(342, 342, 342))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGroterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroterActionPerformed
        letterGrootte = 19;
        txtTest.setFont(new Font("Tahoma", 0, letterGrootte));

    }//GEN-LAST:event_btnGroterActionPerformed

    private void btnKleinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKleinerActionPerformed
        letterGrootte = 12;
        txtTest.setFont(new Font("Tahoma", 0, letterGrootte));

    }//GEN-LAST:event_btnKleinerActionPerformed

    private void btnOpslaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpslaanActionPerformed
        Main.newLettergrootte(letterGrootte);
        setLetterGrootte(Main.getLetterGrootte());
    }//GEN-LAST:event_btnOpslaanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGroter;
    private javax.swing.JButton btnKleiner;
    private javax.swing.JButton btnOpslaan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFormaat;
    private javax.swing.JTextArea txtTest;
    // End of variables declaration//GEN-END:variables
}
