/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import enums.Gebruiker;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import system.CellRenderer;
import system.Database;
import system.Main;

/**
 *
 * @author Dave van Rijn, Klas IS-103, Studentnummer 500714558
 */
public class Startpage extends javax.swing.JPanel {

    /**
     * Creates new form startPage
     */
    public Startpage() {
        initComponents();
        setLetterGrootte(Main.getLetterGrootte());
        CellRenderer.initUI(tblWijzigingen, false);
        Database db = new Database();
        lblGebruiker.setText("Gebruiker: " + Gebruiker.getVolledigeNaam());
        ResultSet rs = db.getRecenteWijzigingen();

        try {
            while (tblWijzigingen.getRowCount() > 0) {
                ((DefaultTableModel) tblWijzigingen.getModel()).removeRow(0);
            }
            int columns = rs.getMetaData().getColumnCount();
            while (rs.next()) {
                Object[] row = new Object[columns];
                for (int i = 1; i <= columns; i++) {
                    row[i - 1] = rs.getObject(i);
                }
                ((DefaultTableModel) tblWijzigingen.getModel()).insertRow(rs.getRow() - 1, row);
            }
            rs.close();
        } catch (SQLException e) {
            Main.showError("052", e);
        }
    }

    private void setLetterGrootte(int grootte) {
        Font font = new Font("Tahoma", 0, grootte);
        btnCategorieen.setFont(font);
        btnGebruiks.setFont(font);
        btnNieuwWijz.setFont(font);
        btnNieuweHypo.setFont(font);
        btnOverzicht.setFont(font);
        jLabel1.setFont(font);
        lblGebruiker.setFont(font);
        btnInstellingen.setFont(font);
        if (grootte == 19) {
            tblWijzigingen.setFont(new Font("Tahoma", 0, 24));
        } else {
            tblWijzigingen.setFont(new Font("Tahoma", 0, 16));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGebruiker = new javax.swing.JLabel();
        btnNieuwWijz = new javax.swing.JButton();
        btnGebruiks = new javax.swing.JButton();
        btnOverzicht = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWijzigingen = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 14), new java.awt.Dimension(0, 14), new java.awt.Dimension(32767, 14));
        btnCategorieen = new javax.swing.JButton();
        btnNieuweHypo = new javax.swing.JButton();
        btnInstellingen = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 500));

        lblGebruiker.setText("Gebruiker");

        btnNieuwWijz.setText("Nieuwe invoer");
        btnNieuwWijz.setToolTipText("Voer een nieuwe uitgave/inkomst in");
        btnNieuwWijz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNieuwWijz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNieuwWijzActionPerformed(evt);
            }
        });

        btnGebruiks.setText("<html><center>Gebruikersinformatie<br />wijzigen</center></html>");
        btnGebruiks.setToolTipText("Wijzig uw gegevens");
        btnGebruiks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGebruiksActionPerformed(evt);
            }
        });

        btnOverzicht.setText("Overzicht");
        btnOverzicht.setToolTipText("Overzicht van alle uitgaven/inkomsten");
        btnOverzicht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOverzichtActionPerformed(evt);
            }
        });

        tblWijzigingen.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblWijzigingen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Datum", "In", "Uit", "Soort"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblWijzigingen.setRowHeight(30);
        jScrollPane1.setViewportView(tblWijzigingen);

        jLabel1.setText("Recente wijzigingen");

        btnCategorieen.setText("Beheer categorieën");
        btnCategorieen.setToolTipText("Beheer de categorieën");
        btnCategorieen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategorieenActionPerformed(evt);
            }
        });

        btnNieuweHypo.setText("Hypotheken");
        btnNieuweHypo.setToolTipText("Beheer de hypotheken");
        btnNieuweHypo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNieuweHypoActionPerformed(evt);
            }
        });

        btnInstellingen.setText("Instellingen");
        btnInstellingen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstellingenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGebruiker)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInstellingen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNieuweHypo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnGebruiks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCategorieen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNieuwWijz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnOverzicht, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCategorieen, btnGebruiks, btnInstellingen, btnNieuwWijz, btnNieuweHypo, btnOverzicht});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblGebruiker))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNieuwWijz, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnOverzicht, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGebruiks, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCategorieen))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(11, 11, 11)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(btnNieuweHypo)
                .addGap(18, 18, 18)
                .addComponent(btnInstellingen)
                .addGap(41, 41, 41))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCategorieen, btnGebruiks, btnInstellingen, btnNieuwWijz, btnNieuweHypo, btnOverzicht});

    }// </editor-fold>//GEN-END:initComponents

    private void btnNieuwWijzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNieuwWijzActionPerformed
        Main.setNewPanel(new NieuweWijziging());
    }//GEN-LAST:event_btnNieuwWijzActionPerformed

    private void btnOverzichtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOverzichtActionPerformed
        Main.setNewPanel(new Overzicht());
    }//GEN-LAST:event_btnOverzichtActionPerformed

    private void btnGebruiksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGebruiksActionPerformed
        Main.setNewPanel(new Gegevens());
    }//GEN-LAST:event_btnGebruiksActionPerformed

    private void btnCategorieenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategorieenActionPerformed
        Main.setNewPanel(new Categorieen());
    }//GEN-LAST:event_btnCategorieenActionPerformed

    private void btnNieuweHypoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNieuweHypoActionPerformed
        Main.setNewPanel(new Hypotheken());
    }//GEN-LAST:event_btnNieuweHypoActionPerformed

    private void btnInstellingenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstellingenActionPerformed
        Main.setNewPanel(new Instellingen());
    }//GEN-LAST:event_btnInstellingenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategorieen;
    private javax.swing.JButton btnGebruiks;
    private javax.swing.JButton btnInstellingen;
    private javax.swing.JButton btnNieuwWijz;
    private javax.swing.JButton btnNieuweHypo;
    private javax.swing.JButton btnOverzicht;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGebruiker;
    private javax.swing.JTable tblWijzigingen;
    // End of variables declaration//GEN-END:variables
}
